//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2016.03.22 at 09:45:02 PM GMT
//


package uk.org.linuxgrotto.tocrunch.api.model;

import java.util.ArrayList;
import java.util.List;


/**
 *
 *         A wrapper for a collection of bank account, credit card or payment processing accounts
 *
 *
 * <p>Java class for accounts complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="accounts">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="bankAccounts" type="{http://api.crunch.co.uk/rest}account" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="creditCards" type="{http://api.crunch.co.uk/rest}account" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="paymentProcessingAccount" type="{http://api.crunch.co.uk/rest}account" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="count" use="required" type="{http://www.w3.org/2001/XMLSchema}long" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */

public class Accounts {

    protected List<Account> bankAccounts;
    protected List<Account> creditCards;
    protected List<Account> paymentProcessingAccounts;

    protected long count;

    /**
     * Gets the value of the bankAccounts property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the bankAccounts property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBankAccounts().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Account }
     *
     *
     */
    public List<Account> getBankAccounts() {
        if (bankAccounts == null) {
            bankAccounts = new ArrayList<Account>();
        }
        return this.bankAccounts;
    }

    /**
     * Gets the value of the creditCards property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the creditCards property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCreditCards().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Account }
     *
     *
     */
    public List<Account> getCreditCards() {
        if (creditCards == null) {
            creditCards = new ArrayList<Account>();
        }
        return this.creditCards;
    }

    /**
     * Gets the value of the paymentProcessingAccount property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the paymentProcessingAccount property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPaymentProcessingAccount().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Account }
     *
     *
     */
    public List<Account> getPaymentProcessingAccounts() {
        if (paymentProcessingAccounts == null) {
            paymentProcessingAccounts = new ArrayList<Account>();
        }
        return this.paymentProcessingAccounts;
    }

    /**
     * Gets the value of the count property.
     *
     */
    public long getCount() {
        return count;
    }

    /**
     * Sets the value of the count property.
     *
     */
    public void setCount(long value) {
        this.count = value;
    }

}
