//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.22 at 09:45:02 PM GMT 
//


package uk.org.linuxgrotto.tocrunch.api.model;

/**
 * 
 *         Represents payments made to sales invoice(s)
 *       
 * 
 * <p>Java class for clientPayment complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="clientPayment">
 *   &lt;complexContent>
 *     &lt;extension base="{http://api.crunch.co.uk/rest}payment">
 *       &lt;sequence>
 *         &lt;element name="client" type="{http://api.crunch.co.uk/rest}client" minOccurs="0"/>
 *         &lt;element name="processingExpense" type="{http://api.crunch.co.uk/rest}expense" minOccurs="0"/>
 *         &lt;element name="salesInvoices" type="{http://api.crunch.co.uk/rest}salesInvoices" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="clientPaymentId" type="{http://www.w3.org/2001/XMLSchema}long" />
 *       &lt;attribute name="currency" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="resourceUrl" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */

public class ClientPayment
    extends Payment
{

    protected Client client;
    protected Expense processingExpense;
    protected SalesInvoices salesInvoices;

    protected Long clientPaymentId;

    protected String currency;

    protected String resourceUrl;

    /**
     * Gets the value of the client property.
     * 
     * @return
     *     possible object is
     *     {@link Client }
     *     
     */
    public Client getClient() {
        return client;
    }

    /**
     * Sets the value of the client property.
     * 
     * @param value
     *     allowed object is
     *     {@link Client }
     *     
     */
    public void setClient(Client value) {
        this.client = value;
    }

    /**
     * Gets the value of the processingExpense property.
     * 
     * @return
     *     possible object is
     *     {@link Expense }
     *     
     */
    public Expense getProcessingExpense() {
        return processingExpense;
    }

    /**
     * Sets the value of the processingExpense property.
     * 
     * @param value
     *     allowed object is
     *     {@link Expense }
     *     
     */
    public void setProcessingExpense(Expense value) {
        this.processingExpense = value;
    }

    /**
     * Gets the value of the salesInvoices property.
     * 
     * @return
     *     possible object is
     *     {@link SalesInvoices }
     *     
     */
    public SalesInvoices getSalesInvoices() {
        return salesInvoices;
    }

    /**
     * Sets the value of the salesInvoices property.
     * 
     * @param value
     *     allowed object is
     *     {@link SalesInvoices }
     *     
     */
    public void setSalesInvoices(SalesInvoices value) {
        this.salesInvoices = value;
    }

    /**
     * Gets the value of the clientPaymentId property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getClientPaymentId() {
        return clientPaymentId;
    }

    /**
     * Sets the value of the clientPaymentId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setClientPaymentId(Long value) {
        this.clientPaymentId = value;
    }

    /**
     * Gets the value of the currency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCurrency() {
        return currency;
    }

    /**
     * Sets the value of the currency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCurrency(String value) {
        this.currency = value;
    }

    /**
     * Gets the value of the resourceUrl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResourceUrl() {
        return resourceUrl;
    }

    /**
     * Sets the value of the resourceUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResourceUrl(String value) {
        this.resourceUrl = value;
    }

}
