//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2016.03.22 at 09:45:02 PM GMT
//


package uk.org.linuxgrotto.tocrunch.api.model;

/**
 *
 *         Represents a director of the company
 *
 *
 * <p>Java class for director complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="director">
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *       &lt;attribute name="directorId" type="{http://www.w3.org/2001/XMLSchema}long" />
 *       &lt;attribute name="directorEmail" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */

public class Director {


    protected String directorName;

    protected Long directorId;

    protected String directorEmail;


    public String getDirectorName() {
        return directorName;
    }

    public void setDirectorName(String directorName) {
        this.directorName = directorName;
    }

    /**
     * Gets the paymentMethodName of the directorId property.
     *
     * @return
     *     possible object is
     *     {@link Long }
     *
     */
    public Long getDirectorId() {
        return directorId;
    }

    /**
     * Sets the paymentMethodName of the directorId property.
     *
     * @param value
     *     allowed object is
     *     {@link Long }
     *
     */
    public void setDirectorId(Long value) {
        this.directorId = value;
    }

    /**
     * Gets the paymentMethodName of the directorEmail property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getDirectorEmail() {
        return directorEmail;
    }

    /**
     * Sets the paymentMethodName of the directorEmail property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setDirectorEmail(String value) {
        this.directorEmail = value;
    }

}
