//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2016.03.22 at 09:45:02 PM GMT
//


package uk.org.linuxgrotto.tocrunch.api.model;

/**
 *
 *         Represents an expense line item
 *
 *
 * <p>Java class for expenseLineItem complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="expenseLineItem">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="expenseTypes" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="benefitingDirector" type="{http://api.crunch.co.uk/rest}director" minOccurs="0"/>
 *         &lt;element name="lineItemDescription" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="lineItemAmount" type="{http://api.crunch.co.uk/rest}amount"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */

public class ExpenseLineItem {

    protected String expenseType;
    protected Director benefitingDirector;

    protected String lineItemDescription;

    protected Amount lineItemAmount;

    /**
     * Gets the value of the expenseTypes property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getExpenseType() {
        return expenseType;
    }

    /**
     * Sets the value of the expenseTypes property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setExpenseType(String value) {
        this.expenseType = value;
    }

    /**
     * Gets the value of the benefitingDirector property.
     *
     * @return
     *     possible object is
     *     {@link Director }
     *
     */
    public Director getBenefitingDirector() {
        return benefitingDirector;
    }

    /**
     * Sets the value of the benefitingDirector property.
     *
     * @param value
     *     allowed object is
     *     {@link Director }
     *
     */
    public void setBenefitingDirector(Director value) {
        this.benefitingDirector = value;
    }

    /**
     * Gets the value of the lineItemDescription property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getLineItemDescription() {
        return lineItemDescription;
    }

    /**
     * Sets the value of the lineItemDescription property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setLineItemDescription(String value) {
        this.lineItemDescription = value;
    }

    /**
     * Gets the value of the lineItemAmount property.
     *
     * @return
     *     possible object is
     *     {@link Amount }
     *
     */
    public Amount getLineItemAmount() {
        return lineItemAmount;
    }

    /**
     * Sets the value of the lineItemAmount property.
     *
     * @param value
     *     allowed object is
     *     {@link Amount }
     *
     */
    public void setLineItemAmount(Amount value) {
        this.lineItemAmount = value;
    }

}
