//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.22 at 09:45:02 PM GMT 
//


package uk.org.linuxgrotto.tocrunch.api.model;

import java.math.BigDecimal;


/**
 * 
 *         Represents an expense
 *       
 * 
 * <p>Java class for expense complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="expense">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="expenseDetails" type="{http://api.crunch.co.uk/rest}expenseDetails"/>
 *         &lt;element name="expenseLineItems" type="{http://api.crunch.co.uk/rest}expenseLineItems" minOccurs="0"/>
 *         &lt;element name="paymentDetails" type="{http://api.crunch.co.uk/rest}paymentDetails"/>
 *         &lt;element name="receipts" type="{http://api.crunch.co.uk/rest}receipts" minOccurs="0"/>
 *         &lt;element name="note" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="expenseId" type="{http://www.w3.org/2001/XMLSchema}long" />
 *       &lt;attribute name="resourceUrl" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="amount" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */

public class Expense {

    protected ExpenseDetails expenseDetails;
    protected ExpenseLineItems expenseLineItems;
    protected PaymentDetails paymentDetails;
    protected Receipts receipts;
    protected String note;

    protected Long expenseId;

    protected String resourceUrl;

    protected BigDecimal amount;

    /**
     * Gets the value of the expenseDetails property.
     * 
     * @return
     *     possible object is
     *     {@link ExpenseDetails }
     *     
     */
    public ExpenseDetails getExpenseDetails() {
        return expenseDetails;
    }

    /**
     * Sets the value of the expenseDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExpenseDetails }
     *     
     */
    public void setExpenseDetails(ExpenseDetails value) {
        this.expenseDetails = value;
    }

    /**
     * Gets the value of the expenseLineItems property.
     * 
     * @return
     *     possible object is
     *     {@link ExpenseLineItems }
     *     
     */
    public ExpenseLineItems getExpenseLineItems() {
        return expenseLineItems;
    }

    /**
     * Sets the value of the expenseLineItems property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExpenseLineItems }
     *     
     */
    public void setExpenseLineItems(ExpenseLineItems value) {
        this.expenseLineItems = value;
    }

    /**
     * Gets the value of the paymentDetails property.
     * 
     * @return
     *     possible object is
     *     {@link PaymentDetails }
     *     
     */
    public PaymentDetails getPaymentDetails() {
        return paymentDetails;
    }

    /**
     * Sets the value of the paymentDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link PaymentDetails }
     *     
     */
    public void setPaymentDetails(PaymentDetails value) {
        this.paymentDetails = value;
    }

    /**
     * Gets the value of the receipts property.
     * 
     * @return
     *     possible object is
     *     {@link Receipts }
     *     
     */
    public Receipts getReceipts() {
        return receipts;
    }

    /**
     * Sets the value of the receipts property.
     * 
     * @param value
     *     allowed object is
     *     {@link Receipts }
     *     
     */
    public void setReceipts(Receipts value) {
        this.receipts = value;
    }

    /**
     * Gets the value of the note property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNote() {
        return note;
    }

    /**
     * Sets the value of the note property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNote(String value) {
        this.note = value;
    }

    /**
     * Gets the value of the expenseId property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getExpenseId() {
        return expenseId;
    }

    /**
     * Sets the value of the expenseId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setExpenseId(Long value) {
        this.expenseId = value;
    }

    /**
     * Gets the value of the resourceUrl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResourceUrl() {
        return resourceUrl;
    }

    /**
     * Sets the value of the resourceUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResourceUrl(String value) {
        this.resourceUrl = value;
    }

    /**
     * Gets the value of the amount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * Sets the value of the amount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setAmount(BigDecimal value) {
        this.amount = value;
    }

}
