//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2016.03.22 at 09:45:02 PM GMT
//


package uk.org.linuxgrotto.tocrunch.api.model;

import java.util.ArrayList;
import java.util.List;


/**
 *
 *         Represents a collection of expense groups, which are collections of exp
 * ense types
 *
 *
 * <p>Java class for expenseTypes complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="expenseTypes">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="expenseGroup" type="{http://api.crunch.co.uk/rest}expenseGroup" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="count" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */

public class ExpenseTypes {

    protected List<ExpenseGroup> expenseGroup;

    protected int count;


    public List<ExpenseGroup> getExpenseGroup() {
        if (expenseGroup == null) {
            expenseGroup = new ArrayList<>();
        }
        return this.expenseGroup;
    }

    /**
     * Gets the value of the count property.
     *
     */
    public int getCount() {
        return count;
    }

    /**
     * Sets the value of the count property.
     *
     */
    public void setCount(int value) {
        this.count = value;
    }

}
