//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2016.03.22 at 09:45:02 PM GMT
//


package uk.org.linuxgrotto.tocrunch.api.model;

import com.bignerdranch.expandablerecyclerview.Model.ParentListItem;

import java.util.ArrayList;
import java.util.List;


/**
 *
 *         Represents groups of expense types
 *
 *
 * <p>Java class for expenseGroup complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="expenseGroup">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="expenseTypes" type="{http://api.crunch.co.uk/rest}expenseTypes" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="count" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="groupName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="displayName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */

public class ExpenseGroup implements ParentListItem {

    protected List<ExpenseType> expenseTypes;

    protected int count;

    protected String groupName;

    protected String displayName;

    public List<ExpenseType> getExpenseTypes() {
        if (expenseTypes == null) {
            expenseTypes = new ArrayList<>();
        }
        return this.expenseTypes;
    }

    @Override
    public List<?> getChildItemList() {
        return expenseTypes;
    }

    public void setChildItemList(List<ExpenseType> expenseTypes) {
        this.expenseTypes = expenseTypes;
    }

    @Override
    public boolean isInitiallyExpanded() {
        return false;
    }

    /**
     * Gets the value of the count property.
     *
     */
    public int getCount() {
        return count;
    }

    /**
     * Sets the value of the count property.
     *
     */
    public void setCount(int value) {
        this.count = value;
    }

    /**
     * Gets the value of the groupName property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getGroupName() {
        return groupName;
    }

    /**
     * Sets the value of the groupName property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setGroupName(String value) {
        this.groupName = value;
    }

    /**
     * Gets the value of the displayName property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getDisplayName() {
        return displayName;
    }

    /**
     * Sets the value of the displayName property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setDisplayName(String value) {
        this.displayName = value;
    }

}
