//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2016.03.22 at 09:45:02 PM GMT
//


package uk.org.linuxgrotto.tocrunch.api.model;

public class PaymentMethod {

    protected String paymentMethodName;
    protected String paymentMethodDisplayName;
    protected String requiredElement;

    public String getPaymentMethodName() {
        return paymentMethodName;
    }


    public void setPaymentMethodName(String paymentMethodName) {
        this.paymentMethodName = paymentMethodName;
    }

    public String getPaymentMethodDisplayName() {
        return paymentMethodDisplayName;
    }

    public void setPaymentMethodDisplayName(String value) {
        this.paymentMethodDisplayName = value;
    }

    public String getRequiredElement() {
        return requiredElement;
    }

    public void setRequiredElement(String value) {
        this.requiredElement = value;
    }

}
