//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.22 at 09:45:02 PM GMT 
//


package uk.org.linuxgrotto.tocrunch.api.model;

import java.util.ArrayList;
import java.util.List;


/**
 * 
 *         A wrapper for a collection of SalesInvoice elements
 *       
 * 
 * <p>Java class for salesInvoices complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="salesInvoices">
 *   &lt;complexContent>
 *     &lt;extension base="{http://api.crunch.co.uk/rest}apiQueryList">
 *       &lt;sequence>
 *         &lt;element name="salesInvoice" type="{http://api.crunch.co.uk/rest}salesInvoice" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */

public class SalesInvoices
    extends ApiQueryList
{

    protected List<SalesInvoice> salesInvoice;

    /**
     * Gets the value of the salesInvoice property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the salesInvoice property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSalesInvoice().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SalesInvoice }
     * 
     * 
     */
    public List<SalesInvoice> getSalesInvoice() {
        if (salesInvoice == null) {
            salesInvoice = new ArrayList<SalesInvoice>();
        }
        return this.salesInvoice;
    }

}
