//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.22 at 09:45:02 PM GMT 
//


package uk.org.linuxgrotto.tocrunch.api.model;

import java.math.BigDecimal;


/**
 * 
 *         Represents a sales invoice
 *       
 * 
 * <p>Java class for salesInvoice complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="salesInvoice">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="salesInvoiceDetails" type="{http://api.crunch.co.uk/rest}salesInvoiceDetails" minOccurs="0"/>
 *         &lt;element name="salesInvoiceLineItems" type="{http://api.crunch.co.uk/rest}salesInvoiceLineItems" minOccurs="0"/>
 *         &lt;element name="clientPayments" type="{http://api.crunch.co.uk/rest}clientPayments" minOccurs="0"/>
 *         &lt;element name="note" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="document" type="{http://api.crunch.co.uk/rest}file" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="salesInvoiceId" type="{http://www.w3.org/2001/XMLSchema}long" />
 *       &lt;attribute name="resourceUrl" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="currency" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="allocatedAmount" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */

public class SalesInvoice {

    protected SalesInvoiceDetails salesInvoiceDetails;
    protected SalesInvoiceLineItems salesInvoiceLineItems;
    protected ClientPayments clientPayments;
    protected String note;
    protected File document;

    protected Long salesInvoiceId;

    protected String resourceUrl;

    protected String currency;

    protected BigDecimal allocatedAmount;

    /**
     * Gets the value of the salesInvoiceDetails property.
     * 
     * @return
     *     possible object is
     *     {@link SalesInvoiceDetails }
     *     
     */
    public SalesInvoiceDetails getSalesInvoiceDetails() {
        return salesInvoiceDetails;
    }

    /**
     * Sets the value of the salesInvoiceDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link SalesInvoiceDetails }
     *     
     */
    public void setSalesInvoiceDetails(SalesInvoiceDetails value) {
        this.salesInvoiceDetails = value;
    }

    /**
     * Gets the value of the salesInvoiceLineItems property.
     * 
     * @return
     *     possible object is
     *     {@link SalesInvoiceLineItems }
     *     
     */
    public SalesInvoiceLineItems getSalesInvoiceLineItems() {
        return salesInvoiceLineItems;
    }

    /**
     * Sets the value of the salesInvoiceLineItems property.
     * 
     * @param value
     *     allowed object is
     *     {@link SalesInvoiceLineItems }
     *     
     */
    public void setSalesInvoiceLineItems(SalesInvoiceLineItems value) {
        this.salesInvoiceLineItems = value;
    }

    /**
     * Gets the value of the clientPayments property.
     * 
     * @return
     *     possible object is
     *     {@link ClientPayments }
     *     
     */
    public ClientPayments getClientPayments() {
        return clientPayments;
    }

    /**
     * Sets the value of the clientPayments property.
     * 
     * @param value
     *     allowed object is
     *     {@link ClientPayments }
     *     
     */
    public void setClientPayments(ClientPayments value) {
        this.clientPayments = value;
    }

    /**
     * Gets the value of the note property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNote() {
        return note;
    }

    /**
     * Sets the value of the note property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNote(String value) {
        this.note = value;
    }

    /**
     * Gets the value of the document property.
     * 
     * @return
     *     possible object is
     *     {@link File }
     *     
     */
    public File getDocument() {
        return document;
    }

    /**
     * Sets the value of the document property.
     * 
     * @param value
     *     allowed object is
     *     {@link File }
     *     
     */
    public void setDocument(File value) {
        this.document = value;
    }

    /**
     * Gets the value of the salesInvoiceId property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getSalesInvoiceId() {
        return salesInvoiceId;
    }

    /**
     * Sets the value of the salesInvoiceId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setSalesInvoiceId(Long value) {
        this.salesInvoiceId = value;
    }

    /**
     * Gets the value of the resourceUrl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResourceUrl() {
        return resourceUrl;
    }

    /**
     * Sets the value of the resourceUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResourceUrl(String value) {
        this.resourceUrl = value;
    }

    /**
     * Gets the value of the currency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCurrency() {
        return currency;
    }

    /**
     * Sets the value of the currency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCurrency(String value) {
        this.currency = value;
    }

    /**
     * Gets the value of the allocatedAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getAllocatedAmount() {
        return allocatedAmount;
    }

    /**
     * Sets the value of the allocatedAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setAllocatedAmount(BigDecimal value) {
        this.allocatedAmount = value;
    }

}
